[package]
name = "ctlab-firmware-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
avrd = { version = "1.0.0", features = ["all-mcus"] }

[lib]
path = "src/lib.rs"

[lints.rust]
missing_docs = "deny"

[lints.rustdoc]
broken_intra_doc_links = "deny"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = "symbols"
