#[allow(unused_imports)]
use super::*;

#[derive(Debug, Clone)]
pub struct ParseContext {
    pub ser_inp_str: String,
    pub ser_inp_ptr: usize,
    pub param_str: String,
    pub param: f32,
    pub param_int: i32,
    pub param_byte: u8,
    pub sub_ch: u8,
    pub current_ch: u8,
    pub slave_ch: u8,
    pub cmd_which: CmdWhich,
    pub verbose: bool,
    pub changed_flag: bool,
    pub ee_unlocked: bool,
    pub modify: u8,
    pub inc_rast: i32,
    pub inc_rast_def: i32,
    pub integrate_ad16: bool,
    pub init_integrate_ad16: bool,
    pub ext_ref: u8,
    pub trig_timer_value: u16,
    pub trig_level: u8,
    pub ee_ser_baud_reg: u8,
    pub err_count: i32,
    pub status: u8,
    pub i2c_slave_adr: u8,
    pub trigger: bool,
    pub led_activity_low: bool,
    pub activity_timer_ticks: u8,
    pub vers1_str: String,
    pub egg_str: String,
    pub param_text_array: Vec<String>,
    pub dac_raw_array: [u16; 8],
    pub dac_value_array: [f32; 8],
    pub offset_array: [i32; 28],
    pub scale_array: [f32; 30],
    pub port_init_array: [u8; 8],
    pub dir_init_array: [u8; 8],
    pub trig_mask_array: [u8; 4],
    pub adc10_raw_array: [i32; 8],
    pub adc_raw_array: [i32; 8],
    pub port_array: [u8; 8],
    pub io_pin_array: [u8; 8],
    pub dir_output_array: [u8; 8],
    pub io_present: bool,
    pub dac12_present: bool,
    pub dac16_present: bool,
    pub dac714_present: bool,
    pub adc16_present: bool,
    pub lcd_present: bool,
    pub base_scale_ad10: f32,
    pub base_scale_ad16: f32,
    pub base_scale_da12: f32,
    pub base_scale_da16: f32,
    pub internal_reference: bool,
    pub trigger_positive_edge: bool,
    pub i2c_byte_reads: VecDeque<u8>,
    pub i2c_word_reads: VecDeque<u16>,
    pub i2c_writes: Vec<(u8, u16)>,
    pub shift_register_writes: Vec<[u8; 8]>,
}

impl Default for ParseContext {
    fn default() -> Self {
        let mut offset_array = [0; 28];
        offset_array[10..=17].fill(-40);

        Self {
            ser_inp_str: String::new(),
            ser_inp_ptr: 0,
            param_str: String::new(),
            param: 0.0,
            param_int: 0,
            param_byte: 0,
            sub_ch: 0,
            current_ch: 0,
            slave_ch: 0,
            cmd_which: CmdWhich::Err,
            verbose: false,
            changed_flag: false,
            ee_unlocked: false,
            modify: 0,
            inc_rast: 4,
            inc_rast_def: 4,
            integrate_ad16: false,
            init_integrate_ad16: false,
            ext_ref: 1,
            trig_timer_value: 0,
            trig_level: 0,
            ee_ser_baud_reg: 51,
            err_count: 0,
            status: 0,
            i2c_slave_adr: 0,
            trigger: false,
            led_activity_low: false,
            activity_timer_ticks: 0,
            vers1_str: String::new(),
            egg_str: String::new(),
            param_text_array: vec![String::new(); 38],
            dac_raw_array: [0; 8],
            dac_value_array: [0.0; 8],
            offset_array,
            scale_array: [
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                0.0,
                100.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                0.0,
                3185.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                200.0,
                3200.0,
            ],
            port_init_array: [0; 8],
            dir_init_array: [0; 8],
            trig_mask_array: [0; 4],
            adc10_raw_array: [0; 8],
            adc_raw_array: [0; 8],
            port_array: [0; 8],
            io_pin_array: [0; 8],
            dir_output_array: [0; 8],
            io_present: false,
            dac12_present: false,
            dac16_present: false,
            dac714_present: false,
            adc16_present: false,
            lcd_present: false,
            base_scale_ad10: 100.0,
            base_scale_ad16: 3185.0,
            base_scale_da12: 200.0,
            base_scale_da16: 3200.0,
            internal_reference: false,
            trigger_positive_edge: false,
            i2c_byte_reads: VecDeque::new(),
            i2c_word_reads: VecDeque::new(),
            i2c_writes: Vec::new(),
            shift_register_writes: Vec::new(),
        }
    }
}
